// <auto-generated />
using System;
using DoAn_WebBanDoChoi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DoAn_WebBanDoChoi.Migrations
{
    [DbContext(typeof(WebBanDoChoiContext))]
    partial class WebBanDoChoiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DoAn_WebBanDoChoi.Models.Account", b =>
                {
                    b.Property<int>("Makh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("makh");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Makh"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ho_ten");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mat_khau");

                    b.Property<DateOnly?>("NgayDangKy")
                        .HasColumnType("date")
                        .HasColumnName("ngay_dang_ky");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("so_dien_thoai");

                    b.HasKey("Makh")
                        .HasName("account_pkey");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "account_email_key")
                        .IsUnique();

                    b.ToTable("account", (string)null);
                });

            modelBuilder.Entity("DoAn_WebBanDoChoi.Models.ChiTietDonHang", b =>
                {
                    b.Property<int>("Madh")
                        .HasColumnType("integer")
                        .HasColumnName("madh");

                    b.Property<int>("Masp")
                        .HasColumnType("integer")
                        .HasColumnName("masp");

                    b.Property<double?>("DonGia")
                        .HasColumnType("double precision")
                        .HasColumnName("don_gia");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("integer")
                        .HasColumnName("so_luong");

                    b.HasKey("Madh", "Masp")
                        .HasName("chi_tiet_don_hang_pkey");

                    b.HasIndex("Masp");

                    b.ToTable("chi_tiet_don_hang", (string)null);
                });

            modelBuilder.Entity("DoAn_WebBanDoChoi.Models.ChiTietGioHang", b =>
                {
                    b.Property<int>("Magh")
                        .HasColumnType("integer")
                        .HasColumnName("magh");

                    b.Property<int>("Masp")
                        .HasColumnType("integer")
                        .HasColumnName("masp");

                    b.Property<double?>("DonGia")
                        .HasColumnType("double precision")
                        .HasColumnName("don_gia");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("integer")
                        .HasColumnName("so_luong");

                    b.HasKey("Magh", "Masp")
                        .HasName("chi_tiet_gio_hang_pkey");

                    b.HasIndex("Masp");

                    b.ToTable("chi_tiet_gio_hang", (string)null);
                });

            modelBuilder.Entity("DoAn_WebBanDoChoi.Models.DonHang", b =>
                {
                    b.Property<int>("Madh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("madh");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Madh"));

                    b.Property<string>("DiaChiGiao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("dia_chi_giao");

                    b.Property<int?>("Makh")
                        .HasColumnType("integer")
                        .HasColumnName("makh");

                    b.Property<DateTime?>("NgayDat")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ngay_dat");

                    b.Property<double?>("TongTien")
                        .HasColumnType("double precision")
                        .HasColumnName("tong_tien");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trang_thai");

                    b.HasKey("Madh")
                        .HasName("don_hang_pkey");

                    b.HasIndex("Makh");

                    b.ToTable("don_hang", (string)null);
                });

            modelBuilder.Entity("DoAn_WebBanDoChoi.Models.GioHang", b =>
                {
                    b.Property<int>("Magh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("magh");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Magh"));

                    b.Property<int?>("Makh")
                        .HasColumnType("integer")
                        .HasColumnName("makh");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ngay_tao");

                    b.HasKey("Magh")
                        .HasName("gio_hang_pkey");

                    b.HasIndex("Makh");

                    b.ToTable("gio_hang", (string)null);
                });

            modelBuilder.Entity("DoAn_WebBanDoChoi.Models.LoaiSanPham", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ma_loai");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaLoai"));

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ten_loai");

                    b.HasKey("MaLoai")
                        .HasName("loai_san_pham_pkey");

                    b.ToTable("loai_san_pham", (string)null);
                });

            modelBuilder.Entity("DoAn_WebBanDoChoi.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId");

                    b.HasIndex(new[] { "RoleName" }, "role_role_name_key")
                        .IsUnique();

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("DoAn_WebBanDoChoi.Models.SanPham", b =>
                {
                    b.Property<int>("Masp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("masp");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Masp"));

                    b.Property<double>("Gia")
                        .HasColumnType("double precision")
                        .HasColumnName("gia");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("hinh_anh");

                    b.Property<int?>("MaLoai")
                        .HasColumnType("integer")
                        .HasColumnName("ma_loai");

                    b.Property<int?>("Math")
                        .HasColumnType("integer")
                        .HasColumnName("math");

                    b.Property<string>("MoTa")
                        .HasColumnType("text")
                        .HasColumnName("mo_ta");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ngay_tao");

                    b.Property<int?>("SoLuongTon")
                        .HasColumnType("integer")
                        .HasColumnName("so_luong_ton");

                    b.Property<string>("Tensp")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("tensp");

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("boolean")
                        .HasColumnName("trang_thai");

                    b.HasKey("Masp")
                        .HasName("san_pham_pkey");

                    b.HasIndex("MaLoai");

                    b.HasIndex("Math");

                    b.ToTable("san_pham", (string)null);
                });

            modelBuilder.Entity("DoAn_WebBanDoChoi.Models.ThuongHieu", b =>
                {
                    b.Property<int>("Math")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("math");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Math"));

                    b.Property<string>("Tenth")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenth");

                    b.HasKey("Math")
                        .HasName("thuong_hieu_pkey");

                    b.ToTable("thuong_hieu", (string)null);
                });

            modelBuilder.Entity("DoAn_WebBanDoChoi.Models.Account", b =>
                {
                    b.HasOne("DoAn_WebBanDoChoi.Models.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("account_role_id_fkey");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DoAn_WebBanDoChoi.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("DoAn_WebBanDoChoi.Models.DonHang", "MadhNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("Madh")
                        .IsRequired()
                        .HasConstraintName("chi_tiet_don_hang_madh_fkey");

                    b.HasOne("DoAn_WebBanDoChoi.Models.SanPham", "MaspNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("Masp")
                        .IsRequired()
                        .HasConstraintName("chi_tiet_don_hang_masp_fkey");

                    b.Navigation("MadhNavigation");

                    b.Navigation("MaspNavigation");
                });

            modelBuilder.Entity("DoAn_WebBanDoChoi.Models.ChiTietGioHang", b =>
                {
                    b.HasOne("DoAn_WebBanDoChoi.Models.GioHang", "MaghNavigation")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("Magh")
                        .IsRequired()
                        .HasConstraintName("chi_tiet_gio_hang_magh_fkey");

                    b.HasOne("DoAn_WebBanDoChoi.Models.SanPham", "MaspNavigation")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("Masp")
                        .IsRequired()
                        .HasConstraintName("chi_tiet_gio_hang_masp_fkey");

                    b.Navigation("MaghNavigation");

                    b.Navigation("MaspNavigation");
                });

            modelBuilder.Entity("DoAn_WebBanDoChoi.Models.DonHang", b =>
                {
                    b.HasOne("DoAn_WebBanDoChoi.Models.Account", "MakhNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("Makh")
                        .HasConstraintName("don_hang_makh_fkey");

                    b.Navigation("MakhNavigation");
                });

            modelBuilder.Entity("DoAn_WebBanDoChoi.Models.GioHang", b =>
                {
                    b.HasOne("DoAn_WebBanDoChoi.Models.Account", "MakhNavigation")
                        .WithMany("GioHangs")
                        .HasForeignKey("Makh")
                        .HasConstraintName("gio_hang_makh_fkey");

                    b.Navigation("MakhNavigation");
                });

            modelBuilder.Entity("DoAn_WebBanDoChoi.Models.SanPham", b =>
                {
                    b.HasOne("DoAn_WebBanDoChoi.Models.LoaiSanPham", "MaLoaiNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaLoai")
                        .HasConstraintName("san_pham_ma_loai_fkey");

                    b.HasOne("DoAn_WebBanDoChoi.Models.ThuongHieu", "MathNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("Math")
                        .HasConstraintName("san_pham_math_fkey");

                    b.Navigation("MaLoaiNavigation");

                    b.Navigation("MathNavigation");
                });

            modelBuilder.Entity("DoAn_WebBanDoChoi.Models.Account", b =>
                {
                    b.Navigation("DonHangs");

                    b.Navigation("GioHangs");
                });

            modelBuilder.Entity("DoAn_WebBanDoChoi.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });

            modelBuilder.Entity("DoAn_WebBanDoChoi.Models.GioHang", b =>
                {
                    b.Navigation("ChiTietGioHangs");
                });

            modelBuilder.Entity("DoAn_WebBanDoChoi.Models.LoaiSanPham", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("DoAn_WebBanDoChoi.Models.Role", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("DoAn_WebBanDoChoi.Models.SanPham", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("ChiTietGioHangs");
                });

            modelBuilder.Entity("DoAn_WebBanDoChoi.Models.ThuongHieu", b =>
                {
                    b.Navigation("SanPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
